# Generated by Django 4.2 on 2026-01-21 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_watchlist_watchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
