# Generated by Django 4.2 on 2026-02-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_watchlist_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
